# Generated by Django 4.2.7 on 2024-04-02 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCountries',
            fields=[
                ('country_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_title', models.CharField(blank=True, default='', max_length=100)),
                ('country_emoji', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
