# Generated by Django 4.2.7 on 2024-03-29 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwnerData',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_email', models.CharField(max_length=60, unique=True)),
                ('owner_password', models.CharField(max_length=200)),
            ],
        ),
    ]
