# Generated by Django 4.2.7 on 2024-04-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessownerdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessOwnerData',
        ),
    ]
