# Generated by Django 4.2.7 on 2024-04-02 16:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_delete_businessownerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwnerData',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_email', models.CharField(max_length=60, unique=True)),
                ('owner_password', models.CharField(max_length=200)),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=200)),
                ('owner_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA')),
                ('company_name', models.CharField(max_length=200)),
                ('company_employees_count', models.CharField(blank=True, choices=[('Від 1 до 25', 'Від 1 до 25'), ('Від 26 до 100', 'Від 26 до 100'), ('Від 101 до 250', 'Від 101 до 250'), ('Понад 251', 'Понад 251')], max_length=14)),
                ('promo', models.CharField(blank=True, max_length=50)),
                ('company_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businesscountries')),
            ],
        ),
    ]
