# Generated by Django 4.2.7 on 2024-04-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_businessownerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessownerdata',
            name='company_employees_count',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
