# Generated by Django 4.2.7 on 2024-04-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businessownerdata_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessownerdata',
            name='owner_password',
        ),
    ]
