# Generated by Django 4.2.7 on 2024-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businessownerdata_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessownerdata',
            old_name='owner_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='businessownerdata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='businessownerdata',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='businessownerdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='businessownerdata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessownerdata',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessownerdata',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessownerdata',
            name='owner_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
