# Generated by Django 4.2.7 on 2024-04-09 04:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_rename_owner_email_businessownerdata_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='businessownerdata',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
