# Generated by Django 4.2.7 on 2024-04-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_businessownerdata_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='businessownerdata',
            managers=[
            ],
        ),
    ]
