# Generated by Django 4.2.7 on 2024-04-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_businessownerdata_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessownerdata',
            name='owner_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
