# Generated by Django 4.2.7 on 2024-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_businessownerdata_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessownerdata',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
