# Generated by Django 4.2.7 on 2024-04-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_businessownerdata_is_legal_info_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettingsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_receipt_email', models.EmailField(default='', max_length=150)),
                ('company_codes', models.FileField(upload_to='codes/%Y/%m/%d')),
                ('is_api_handle_allowed', models.BooleanField(default=False)),
                ('promo_codes', models.CharField(default='', max_length=200)),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.companylegalinformation')),
            ],
        ),
    ]
