# Generated by Django 4.2.7 on 2024-04-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_companysettingsinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysettingsinfo',
            old_name='promo_codes',
            new_name='promo_code',
        ),
    ]
