# Generated by Django 4.2.7 on 2024-04-30 03:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_rename_promo_codes_companysettingsinfo_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicies',
            fields=[
                ('policy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_title', models.CharField(default='', max_length=150)),
                ('policy_description', models.TextField(blank=True, default='', null=True)),
                ('track_costs', models.CharField(choices=[('cost_notice', 'Нотатка про витрати'), ('cost_code', 'Код витрат')], default=('cost_notice', 'Нотатка про витрати'), max_length=11)),
                ('cost_level_track', models.CharField(choices=[('', ''), ('individual_level', 'Індивідувальний рівень'), ('group_level', 'Груповий рівень')], default=('', ''), max_length=16)),
                ('drive_day_and_time', models.CharField(choices=[('only_work_day', 'Тільки будні'), ('user_settings', 'Налаштування користувачів')], default=('only_work_day', 'Тільки будні'), max_length=13)),
                ('drive_places', models.CharField(choices=[('to_from_certain_locations', 'До або з певних локацій'), ('only_from_locations', 'Тільки з певних локацій'), ('only_to_locations', 'Тільки до певних локацій'), ('between_locations', 'Між певними локаціями')], default=('to_from_certain_locations', 'До або з певних локацій'), max_length=25)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.companylegalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='TaxiLocation',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radius', models.CharField(choices=[('0.5', '0.5км'), ('1', '1км'), ('1.5', '1.5км'), ('2', '2км'), ('2.5', '2.5км'), ('3', '3км'), ('3.5', '3.5км'), ('4', '4км'), ('4.5', '4.5км'), ('5', '5км'), ('10', '10км'), ('20', '20км'), ('30', '30км'), ('40', '40км'), ('50', '50км'), ('60', '60км'), ('70', '70км'), ('80', '80км'), ('90', '90км'), ('100', '100км')], default=('0.5', '0.5км'), max_length=10)),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.companypolicies')),
            ],
        ),
    ]
