# Generated by Django 4.2.7 on 2024-05-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_companypolicies_taxilocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicies',
            name='kind_service',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companypolicies',
            name='drive_day_and_time',
            field=models.CharField(choices=[('', ''), ('only_work_day', 'Тільки будні'), ('user_settings', 'Налаштування користувачів')], default=('', ''), max_length=13),
        ),
        migrations.AlterField(
            model_name='companypolicies',
            name='drive_places',
            field=models.CharField(choices=[('', ''), ('to_from_certain_locations', 'До або з певних локацій'), ('only_from_locations', 'Тільки з певних локацій'), ('only_to_locations', 'Тільки до певних локацій'), ('between_locations', 'Між певними локаціями')], default=('', ''), max_length=25),
        ),
        migrations.AlterField(
            model_name='companypolicies',
            name='track_costs',
            field=models.CharField(choices=[('', ''), ('cost_notice', 'Нотатка про витрати'), ('cost_code', 'Код витрат')], default=('', ''), max_length=11),
        ),
    ]
