# Generated by Django 4.2.7 on 2024-05-03 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_companypolicies_kind_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoltServices',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_img', models.ImageField(default='', upload_to='media/bolt_services')),
                ('service_title', models.CharField(default='', max_length=35)),
                ('service_description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='companypolicies',
            name='kind_service',
        ),
        migrations.AddField(
            model_name='companypolicies',
            name='kind_service',
            field=models.ManyToManyField(to='business.boltservices'),
        ),
    ]
