# Generated by Django 4.2.7 on 2024-05-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_boltservices_remove_companypolicies_kind_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boltservices',
            name='service_img',
            field=models.URLField(default=''),
        ),
    ]
