# Generated by Django 4.2.7 on 2024-01-08 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetAddress',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=155, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='couriermaininfo',
            name='courier_fleet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courier.fleetaddress'),
            preserve_default=False,
        ),
    ]
