# Generated by Django 4.2.7 on 2024-01-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_fleetaddress_couriermaininfo_courier_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriermaininfo',
            name='courier_fleet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.fleetaddress'),
        ),
    ]
