# Generated by Django 4.2.7 on 2024-01-09 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_alter_couriermaininfo_courier_fleet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('method_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_title', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierDocumentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_name', models.CharField(max_length=150)),
                ('iban_number', models.CharField(max_length=40)),
                ('identification_number', models.CharField(max_length=11)),
                ('bank_card_certificate', models.ImageField(default=False, upload_to='documents/certificates')),
                ('document_image', models.ImageField(default=False, upload_to='documents/passports')),
                ('medicine_card_image', models.ImageField(default=False, upload_to='documents/medicine_cards')),
                ('courier_image', models.ImageField(default=False, upload_to='documents/photos')),
                ('has_bag', models.BooleanField(default=False)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.couriermaininfo')),
                ('delivery_method', models.ManyToManyField(to='courier.deliverymethod')),
            ],
        ),
    ]
