# Generated by Django 4.2.7 on 2024-02-07 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryZones',
            fields=[
                ('zone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='drivercountries',
            name='country_zone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='driver.countryzones'),
            preserve_default=False,
        ),
    ]
