# Generated by Django 4.2.7 on 2024-02-21 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCars',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DriverCarModels',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('car_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.drivercars')),
            ],
        ),
        migrations.CreateModel(
            name='DriverCarInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_first_name', models.CharField(max_length=70)),
                ('driver_last_name', models.CharField(max_length=80)),
                ('referral_code', models.CharField(default='', max_length=20, null=True)),
                ('driver_has_own_car', models.BooleanField(default=True)),
                ('driver_car', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='driver.drivercarmodels')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
