# Generated by Django 4.2.7 on 2024-02-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_drivercars_drivercarmodels_drivercarinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercarmodels',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.drivercars'),
        ),
    ]
