# Generated by Django 4.2.7 on 2024-03-07 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_drivercarinfo_driver_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercarinfo',
            name='driver_car_created_year',
            field=models.CharField(blank=True, choices=[('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='DriverCarDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_license', models.FileField(upload_to='docs/license/%Y/%m/%d/')),
                ('driver_photo', models.FileField(upload_to='docs/photos/%Y/%m/%d/')),
                ('driver_tech_passport', models.FileField(upload_to='docs/tech_passports/%Y/%m/%d/')),
                ('insurance_policy', models.FileField(upload_to='docs/insurance_policy/%Y/%m/%d/')),
                ('driver_car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.drivercarinfo')),
            ],
        ),
    ]
