# Generated by Django 4.2.7 on 2024-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_alter_drivercarinfo_driver_car_created_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercardocuments',
            name='driver_insurance_policy',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='drivercardocuments',
            name='driver_license_expiration_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='drivercardocuments',
            name='driver_tech_passport_expiration_time',
            field=models.DateField(auto_now=True),
        ),
    ]
