# Generated by Django 4.2.7 on 2024-03-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_drivercardocuments_driver_insurance_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivercardocuments',
            name='driver_insurance_policy',
        ),
        migrations.AddField(
            model_name='drivercardocuments',
            name='driver_insurance_policy_expiration_time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_license',
            field=models.FileField(default=None, null=True, upload_to='docs/license/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_license_expiration_time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_photo',
            field=models.FileField(default=None, null=True, upload_to='docs/photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_tech_passport',
            field=models.FileField(default=None, null=True, upload_to='docs/tech_passports/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_tech_passport_expiration_time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='insurance_policy',
            field=models.FileField(default=None, null=True, upload_to='docs/insurance_policy/%Y/%m/%d/'),
        ),
    ]
