# Generated by Django 4.2.7 on 2024-03-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_remove_drivercardocuments_driver_insurance_policy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivercardocuments',
            old_name='insurance_policy',
            new_name='driver_insurance_policy',
        ),
    ]
