# Generated by Django 4.2.7 on 2024-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_rename_insurance_policy_drivercardocuments_driver_insurance_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_insurance_policy',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='docs/insurance_policy/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_license',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='docs/license/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_photo',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='docs/photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_tech_passport',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='docs/tech_passports/%Y/%m/%d/'),
        ),
    ]
