# Generated by Django 4.2.7 on 2024-03-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_alter_drivercardocuments_driver_insurance_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_insurance_policy_expiration_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_license_expiration_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='drivercardocuments',
            name='driver_tech_passport_expiration_time',
            field=models.DateField(null=True),
        ),
    ]
