# Generated by Django 4.2.7 on 2024-03-20 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_alter_drivercardocuments_driver_insurance_policy_expiration_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPaymentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipn_number', models.CharField(max_length=10, unique=True)),
                ('bank_card_owner_name', models.CharField(max_length=200)),
                ('iban_number', models.CharField(max_length=100)),
                ('driver_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
