# Generated by Django 4.2.7 on 2024-01-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_articles_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='support.articlecategories'),
        ),
    ]
