# Generated by Django 4.2.7 on 2023-11-29 07:18

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoltPartner',
            fields=[
                ('partner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_niche', models.CharField(choices=[('Заклад харчування', 'Заклад харчування'), ('Продуктовий магазин', 'Продуктовий магазин'), ('Крамниця', 'Крамниця'), ('Інший роздрібний магазин', 'Інший роздрібний магазин')], max_length=65)),
                ('partner_email', models.EmailField(max_length=155)),
                ('partner_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA')),
                ('is_agree_with_confidence', models.BooleanField(default=False)),
            ],
        ),
    ]
