# Generated by Django 4.2.7 on 2023-12-06 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_boltpartner_is_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('country_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_flag', models.URLField(blank=True)),
                ('country_official_name', models.CharField(max_length=150)),
                ('country_phone_code', models.CharField(max_length=6)),
                ('country_native_name', models.CharField(max_length=100)),
            ],
        ),
    ]
