# Generated by Django 4.2.7 on 2023-12-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_countrycode_country_flag_unicode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrycode',
            name='country_flag_unicode',
        ),
    ]
