# Generated by Django 4.2.7 on 2023-12-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycode',
            name='country_phone_code',
            field=models.CharField(max_length=20),
        ),
    ]
