# Generated by Django 4.2.7 on 2023-12-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_remove_countrycode_country_flag_unicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='country_emoji_flag',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
