# Generated by Django 4.2.7 on 2023-12-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0004_alter_countrycode_country_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='country_flag_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrycode',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
    ]
