# Generated by Django 4.2.7 on 2023-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0004_countrycode_country_emoji_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
