# Generated by Django 4.2.7 on 2023-12-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0005_countrycode_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineCategory',
            fields=[
                ('category_id', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='boltpartner',
            name='partner_cuisine',
        ),
        migrations.AddField(
            model_name='boltpartner',
            name='partner_cuisine',
            field=models.ManyToManyField(related_name='category', to='index_page.cuisinecategory'),
        ),
    ]
