# Generated by Django 4.2.7 on 2023-12-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0006_cuisinecategory_remove_boltpartner_partner_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisinecategory',
            name='category_title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
