# Generated by Django 4.2.7 on 2024-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0007_cuisinecategory_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boltpartner',
            name='is_restaurant',
        ),
        migrations.AddField(
            model_name='boltpartner',
            name='registration_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
