# Generated by Django 4.2.7 on 2024-02-05 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScooterReportModel',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scooter_img', models.ImageField(null=True, upload_to='report/images')),
                ('city', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('rent_company', models.CharField(choices=[('Bolt', 'Bolt'), ('Bird', 'Bird'), ('Lime', 'Lime'), ('Tier', 'Tier'), ('Voi', 'Voi'), ('Wind', 'Wind'), ('Інше', 'Інше')], max_length=10)),
                ('other_rent_company', models.CharField(default=None, max_length=50, null=True)),
                ('scooter_id', models.CharField(max_length=10)),
                ('problem_desc', models.TextField(default=None, null=True)),
            ],
        ),
    ]
