# Generated by Django 4.2.7 on 2024-02-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooterreportmodel',
            name='rent_company',
            field=models.CharField(choices=[('Bolt', 'Bolt'), ('Bird', 'Bird'), ('Lime', 'Lime'), ('Tier', 'Tier'), ('Voi', 'Voi'), ('Wind', 'Wind'), ('Інше', 'Інше')]),
        ),
    ]
