# Generated by Django 4.2.7 on 2024-02-06 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0002_alter_scooterreportmodel_rent_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherReportModel',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rent_company', models.CharField(choices=[('Bolt', 'Bolt'), ('Bird', 'Bird'), ('Lime', 'Lime'), ('Tier', 'Tier'), ('Voi', 'Voi'), ('Wind', 'Wind'), ('Інше', 'Інше')])),
                ('other_rent_company', models.CharField(default=None, max_length=50, null=True)),
                ('problem_desc', models.TextField(default=None, null=True)),
            ],
        ),
    ]
